#####
# Mystic Prompt Configuration
#####


# This is a mess.
# todo: clean up mess.


## System

# Render segments in parallel to speed up.
# Uses mktemp(1) temporary files. Best used
# with tmpfs or other in-memory fs to avoid
# unnecessary spam on your SSD.
MYSTIC_BGRENDER=false


## General display parameters

# Configure visual elements for each supported $TERM
MYSTIC_PLATFORM_NAME="$(uname -s)"
MYSTIC_TERM_SIGNATURE="${MYSTIC_PLATFORM_NAME}${LANG}${TERM}${COLORTERM}"
# MYSTIC_VTY_SIGNATURE_OPENBSD='OpenBSDvt220'
# MYSTIC_VTY_SIGNATURE_FREEBSD='FreeBSDC.UTF-8xterm'
# MYSTIC_VTY_SIGNATURE_LINUX='Linuxen_US.UTF-8linux'

MYSTIC_GLOBAL_TEXT_ATTR="bold"
#MYSTIC_GLOBAL_TEXT_ATTR=""

# Regardless of how many widgets are enabled,
# this is the minimum length of the top frame.
# Default: 23
# Consider:
#
# .-----[o^B]-[0OoL]-[oM.S]- -[Sun-30-02:30]-
# : 127 [root@samadhi] - [.../usr/local/sbin]# ls -la
#
# .--[0OoL]----------------- -[Sun-30-02:30]-
# : ...-issue-1987 3:0 idx.notup:4 tree.rm:2 untracked:7
# :. [root@samadhi] - [.../usr/local/sbin]# ls -la
#
MYSTIC_MIN_FRAME_LENGTH=23

# Max PWD length
MYSTIC_MAXLENGTH_PWD=27

# Max length of branch name to display
MYSTIC_MAXLENGTH_GIT=23

# Outshells
MYSTIC_GLYPH_RANGER='rg'
MYSTIC_GLYPH_MC='mc'

# Base Frame
MYSTIC_GLYPH_LB='['
MYSTIC_GLYPH_RB=']'
MYSTIC_GLYPH_AT='@'
MYSTIC_GLYPH_SLASH='/'

# git
MYSTIC_GLYPH_GIT_WHOSEP='.'
MYSTIC_GLYPH_GIT_NUMSEP=':'

# Input
MYSTIC_GLYPH_ROOT_INPUT='# '


# Select by known terminal signatures
# @TODO: Needs a lot of work yet
case ${MYSTIC_TERM_SIGNATURE} in


	# Assume if it can do at least 256color then it
	# can also do UTF-8.  Same w/ $TRUECOLOR.

	# Why?

	# Because *2*0*2*1*, that's why.

	# Because if you're not spooning with a DEC Alpha
	# you have probably C-A-F7'd out of your framebuffer
	# vty, nice though it is to reminisce, back into
	# present times where we have 256color xterms and
	# are sufficiently internationalized and inclusive
	# for GNU/Linux to find itself distributed with
	# UTF-8 enabled everywhere by default.

	# My oh my what a time to be alive.

  # I am a unicorn. Behold my glitter.


#	*truecolor*)
# 	todo: ... sooon ...
#		MYSTIC_COLOR_MODE=24BIT
#		;;

	*256color*)

		MYSTIC_COLOR_MODE=256

		### Outshells
		MYSTIC_COLOR_RANGER="${MYSTIC_GLOBAL_TEXT_ATTR} xt 550"
		MYSTIC_COLOR_MC="${MYSTIC_GLOBAL_TEXT_ATTR} xt 550"
		#

		### Base Frame
		MYSTIC_GLYPH_ELLIPSIS='…'
		MYSTIC_GLYPH_LINE_H='─'
		MYSTIC_GLYPH_CORNER_TL='┌'
		MYSTIC_GLYPH_LINE_V='│'
		MYSTIC_GLYPH_CORNER_BL='└'
		MYSTIC_COLOR_PUNCTUATION="${MYSTIC_GLOBAL_TEXT_ATTR} xt 222"
		#

		###  Graphing
		MYSTIC_GRAPH_GLYPHS='▁▂▂▃▃▄▅▆▇█'
		#
		# Battery graph
		MYSTIC_GLYPH_BATTERY='ᵇ'
		MYSTIC_GLYPH_SPACER='·'
		MYSTIC_GLYPH_CHARGING='↑'
		MYSTIC_GLYPH_DISCHARGING='↓'
		MYSTIC_GLYPH_FULL='☻'
		MYSTIC_GLYPH_UNKNOWN='‽'
		MYSTIC_GRADIENT_BATTERY_CODE="BCA"
		declare -a MYSTIC_GRADIENT_BATTERY
		#MYSTIC_GRADIENT_BATTERY_CODE="AAB"
		MYSTIC_COLOR_CHARGING="${MYSTIC_GLOBAL_TEXT_ATTR} xt 055"
		MYSTIC_COLOR_DISCHARGING="${MYSTIC_GLOBAL_TEXT_ATTR} xt 033"
		MYSTIC_COLOR_GRAPH_LABEL="${MYSTIC_GLOBAL_TEXT_ATTR} xt 222"
		#
		# Load graph
		MYSTIC_GLYPH_LOAD='ˡ'
		declare -a MYSTIC_GRADIENT_LOAD
		MYSTIC_GRADIENT_LOAD_CODE="ABC"
		#
		# Memory graph
		MYSTIC_GLYPH_MEMORY='ᵐ'
		MYSTIC_GLYPH_SWAP='ˢ'
		declare -a MYSTIC_GRADIENT_MEMORY
		MYSTIC_GRADIENT_MEMORY_CODE="ABC"
		declare -a MYSTIC_GRADIENT_SWAP
		MYSTIC_GRADIENT_SWAP_CODE="ACB"
		#

		### Clock
		MYSTIC_GLYPH_TIMESEP=':'
		MYSTIC_COLOR_DAYNAME="${MYSTIC_GLOBAL_TEXT_ATTR} xt 115"
		MYSTIC_COLOR_DATE="${MYSTIC_GLOBAL_TEXT_ATTR} xt 005"
		MYSTIC_COLOR_TIME="${MYSTIC_GLOBAL_TEXT_ATTR} xt 115"
		#

		### Git
		MYSTIC_COLOR_GITBRANCH_TEXT="${MYSTIC_GLOBAL_TEXT_ATTR} xt 033"
		MYSTIC_COLOR_GITBRANCH_CAPS="${MYSTIC_GLOBAL_TEXT_ATTR} xt 044"
		MYSTIC_COLOR_GITBRANCH_NUM="${MYSTIC_GLOBAL_TEXT_ATTR} xt 055"
		MYSTIC_COLOR_GITSTATUS_NUM="${MYSTIC_GLOBAL_TEXT_ATTR} xt 550"
		MYSTIC_COLOR_GITSTATUS_WHO="${MYSTIC_GLOBAL_TEXT_ATTR} xt 505"
		MYSTIC_COLOR_GITSTATUS_WHAT="${MYSTIC_GLOBAL_TEXT_ATTR} xt 303"
		#

		### Exit Code
		MYSTIC_COLOR_OK_HIGH="${MYSTIC_GLOBAL_TEXT_ATTR} xt 555"
		MYSTIC_COLOR_OK_MID="${MYSTIC_GLOBAL_TEXT_ATTR} xt 005"
		MYSTIC_COLOR_OK_LOW="${MYSTIC_GLOBAL_TEXT_ATTR} xt 003"
		MYSTIC_COLOR_ERROR_HIGH="${MYSTIC_GLOBAL_TEXT_ATTR} xt 555"
		MYSTIC_COLOR_ERROR_MID="${MYSTIC_GLOBAL_TEXT_ATTR} xt 500"
		MYSTIC_COLOR_ERROR_LOW="${MYSTIC_GLOBAL_TEXT_ATTR} xt 300"
		MYSTIC_COLOR_EXITCODE="${MYSTIC_GLOBAL_TEXT_ATTR} xt 555"
		#

		### PWD
		MYSTIC_COLOR_PATH_PWD="${MYSTIC_GLOBAL_TEXT_ATTR} xt 050"
		MYSTIC_COLOR_PATH_PATH="${MYSTIC_GLOBAL_TEXT_ATTR} xt 030"
		#

		### User@Host & Input Pip
		MYSTIC_COLOR_HOSTNAME="${MYSTIC_GLOBAL_TEXT_ATTR} xt 303"
		MYSTIC_COLOR_ROOT_USERNAME="bxt 500 ${MYSTIC_GLOBAL_TEXT_ATTR} xt 550"
		MYSTIC_COLOR_ROOT_INPUT="${MYSTIC_GLOBAL_TEXT_ATTR} xt 500"
		MYSTIC_COLOR_USERNAME="${MYSTIC_GLOBAL_TEXT_ATTR} xt 505"
		MYSTIC_COLOR_INPUT="${MYSTIC_GLOBAL_TEXT_ATTR} xt 005"
		MYSTIC_GLYPH_INPUT='∙ '
		#

		;;

	# Default to 16 color, basic charset
	*)
		MYSTIC_COLOR_MODE=16
		MYSTIC_COLOR_RANGER="${MYSTIC_GLOBAL_TEXT_ATTR} bright yellow"
		MYSTIC_COLOR_MC="${MYSTIC_GLOBAL_TEXT_ATTR} bright yellow"
		MYSTIC_GLYPH_SPACER='-'
		MYSTIC_GLYPH_CHARGING='^'
		MYSTIC_GLYPH_DISCHARGING='.'
		MYSTIC_GLYPH_FULL='*'
		MYSTIC_GLYPH_UNKNOWN='?'
		MYSTIC_GLYPH_ELLIPSIS='...'
		MYSTIC_GLYPH_LINE_H='-'
		MYSTIC_GLYPH_CORNER_TL='.'
		MYSTIC_GLYPH_LINE_V=':'
		MYSTIC_GLYPH_CORNER_BL='.'
		MYSTIC_GLYPH_TIMESEP=':'
		MYSTIC_GLYPH_MEMORY='m'
		MYSTIC_GLYPH_SWAP='s'
		MYSTIC_GLYPH_LOAD='l'
		MYSTIC_GLYPH_BATTERY='b'
		MYSTIC_GRAPH_GLYPHS='..oooOOO00'
		MYSTIC_GRADIENT_COLORS=("${MYSTIC_GLOBAL_TEXT_ATTR} green" \
														"${MYSTIC_GLOBAL_TEXT_ATTR} bright yellow" \
														"${MYSTIC_GLOBAL_TEXT_ATTR} bright purple" \
														"${MYSTIC_GLOBAL_TEXT_ATTR} bright red")
		MYSTIC_GRADIENT_BATTERY_CODE='3322211100'
		MYSTIC_GRADIENT_MEMORY_CODE='0011122233'
		MYSTIC_GRADIENT_SWAP_CODE='0011122233'
		MYSTIC_GRADIENT_LOAD_CODE='0011122233'
		MYSTIC_COLOR_PUNCTUATION="${MYSTIC_GLOBAL_TEXT_ATTR} bright black"
		MYSTIC_COLOR_FRAME=''
		MYSTIC_COLOR_CHARGING="${MYSTIC_GLOBAL_TEXT_ATTR} bright cyan"
		MYSTIC_COLOR_DISCHARGING="${MYSTIC_GLOBAL_TEXT_ATTR} cyan"
		MYSTIC_COLOR_GRAPH_LABEL="${MYSTIC_GLOBAL_TEXT_ATTR} bright black"
		MYSTIC_COLOR_DAYNAME="${MYSTIC_GLOBAL_TEXT_ATTR} bright blue"
		MYSTIC_COLOR_DATE="${MYSTIC_GLOBAL_TEXT_ATTR} blue"
		MYSTIC_COLOR_TIME="${MYSTIC_GLOBAL_TEXT_ATTR} bright blue"
		MYSTIC_COLOR_OK_HIGH="${MYSTIC_GLOBAL_TEXT_ATTR} bright white"
		MYSTIC_COLOR_OK_MID="${MYSTIC_GLOBAL_TEXT_ATTR} bright blue"
		MYSTIC_COLOR_OK_LOW="${MYSTIC_GLOBAL_TEXT_ATTR} blue"
		MYSTIC_COLOR_ERROR_HIGH="${MYSTIC_GLOBAL_TEXT_ATTR} bright white"
		MYSTIC_COLOR_ERROR_MID="${MYSTIC_GLOBAL_TEXT_ATTR} bright red"
		MYSTIC_COLOR_ERROR_LOW="${MYSTIC_GLOBAL_TEXT_ATTR} red"
		MYSTIC_COLOR_EXITCODE="${MYSTIC_GLOBAL_TEXT_ATTR} bright red"
		MYSTIC_COLOR_GITBRANCH_TEXT="${MYSTIC_GLOBAL_TEXT_ATTR} cyan"
		MYSTIC_COLOR_GITBRANCH_CAPS="${MYSTIC_GLOBAL_TEXT_ATTR} bright cyan"
		MYSTIC_COLOR_GITBRANCH_NUM="${MYSTIC_GLOBAL_TEXT_ATTR} bright white"
		MYSTIC_COLOR_GITSTATUS_NUM="${MYSTIC_GLOBAL_TEXT_ATTR} bright yellow"
		MYSTIC_COLOR_GITSTATUS_WHO="${MYSTIC_GLOBAL_TEXT_ATTR} bright purple"
		MYSTIC_COLOR_GITSTATUS_WHAT="${MYSTIC_GLOBAL_TEXT_ATTR} purple"
		MYSTIC_COLOR_HOSTNAME="${MYSTIC_GLOBAL_TEXT_ATTR} purple"
		MYSTIC_COLOR_PATH_PWD="${MYSTIC_GLOBAL_TEXT_ATTR} bright green"
		MYSTIC_COLOR_PATH_PATH="${MYSTIC_GLOBAL_TEXT_ATTR} green"
		MYSTIC_COLOR_ROOT_USERNAME="${MYSTIC_GLOBAL_TEXT_ATTR} bred bright yellow"
		MYSTIC_COLOR_ROOT_INPUT="${MYSTIC_GLOBAL_TEXT_ATTR} bright red"
		MYSTIC_GLYPH_ROOT_INPUT='# '
		MYSTIC_COLOR_USERNAME="${MYSTIC_GLOBAL_TEXT_ATTR} bright purple"
		MYSTIC_COLOR_INPUT="${MYSTIC_GLOBAL_TEXT_ATTR} bright blue"
		MYSTIC_GLYPH_INPUT='$ '

		;;

esac

##
